export type Concept = { id:string; label:string; aliases:string[]; type:string; definition?:string; external_ids:Record<string,string>; tags:string[]; pack_id:string|null };
export type RelationType = { id:string; label:string; inverse_label:string|null; family:string; directed:boolean; symmetric:boolean; transitive:boolean; incompatible_with:string[]; subject_types:string[]; object_types:string[]; hierarchy_weight:-1|0|1; description:string };
export type Proposition = { id:string; subject:string; relation:string|{free:string}; object:string; confidence:1|2|3|4|5|null; justification:string|null; anchors:{source_id:string;locator?:string}[]; learned_at:string; holds_from:string|null; holds_to:string|null; status:"asserted"|"implied"|"disputed"|"retracted"; derived_from:string[]|null };
export type MapDoc = { id:string; title:string; focus_question:string; genre:"concept"; pack_id:string; concepts:Pick<Concept,"id"|"label"|"type"|"pack_id">[]; propositions:Proposition[]; layout:Record<string,{x:number;y:number}>; submaps:Record<string,string>; meta:{created_at:string;last_saved_at:string;session_seconds:number;edit_count:number;added_by:{typed:number;drawn:number;accepted_inference:number}} };
export type Pack = { id:string; title?:string; concepts:Concept[]; relations:RelationType[]; alias_table?:{relations?:Record<string,string>;concepts?:Record<string,string>}; inference?:{inheritable_relations:string[];inherit_along:string} };
const norm=(s:string)=>s.trim().replace(/\s+/g," ").toLowerCase();
const rid=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
function indexes(pack:Pack){const c=new Map<string,Concept>(); for(const x of pack.concepts){c.set(norm(x.label),x); for(const a of x.aliases||[])c.set(norm(a),x); } const r=new Map<string,string>(); for(const x of pack.relations){r.set(norm(x.label),x.id); if(x.inverse_label)r.set(norm(x.inverse_label),`!${x.id}`)} for(const [a,v] of Object.entries(pack.alias_table?.relations||{}))r.set(norm(a),v); return {c,r};}
const relLabel=(r:string|{free:string}, pack:Pack)=>typeof r==="string"?(pack.relations.find(x=>x.id===r)?.label||r):r.free;
const conceptLabel=(id:string,pack:Pack,map?:MapDoc)=>map?.concepts.find(x=>x.id===id)?.label||pack.concepts.find(x=>x.id===id)?.label||id;
function freshMap(pack:Pack, now:string):MapDoc{return {id:"map-"+rid(now),title:"Untitled map",focus_question:"",genre:"concept",pack_id:pack.id,concepts:[],propositions:[],layout:{},submaps:{},meta:{created_at:now,last_saved_at:now,session_seconds:0,edit_count:0,added_by:{typed:0,drawn:0,accepted_inference:0}}};}
export function parseSentences(text:string,pack:Pack, previous?:MapDoc, now:string=new Date().toISOString()):MapDoc{
 const old=previous||freshMap(pack,now), defaults=freshMap(pack,now), ix=indexes(pack), out=freshMap(pack,old.meta?.created_at||now); out.id=old.id||defaults.id; out.title=old.title||defaults.title; out.focus_question=old.focus_question||""; out.meta={...defaults.meta,...old.meta,added_by:{...defaults.meta.added_by,...old.meta?.added_by},last_saved_at:now}; const priorProps=old.propositions||[],byKey=new Map(priorProps.map(p=>[`${p.subject}|${JSON.stringify(p.relation)}|${p.object}`,p])),usedIds=new Set(priorProps.map(p=>p.id));let idCounter=1;const nextId=()=>{while(usedIds.has(`p-${idCounter}`))idCounter++;const id=`p-${idCounter++}`;usedIds.add(id);return id;};
 const concepts=new Map<string,Pick<Concept,"id"|"label"|"type"|"pack_id">>((old.concepts||[]).map(c=>[c.id,c]));
 const getConcept=(raw:string)=>{const c=ix.c.get(norm(raw)); if(c){const v={id:c.id,label:c.label,type:c.type,pack_id:c.pack_id};concepts.set(c.id,v);return c.id;} const id="novel:"+rid(norm(raw)); concepts.set(id,{id,label:raw.trim(),type:"novel",pack_id:null});return id;};
 for(const line of text.split(/\r?\n/)){const t=line.trim(); if(!t)continue; if(t.startsWith("?")){out.focus_question=t.slice(1).trim();continue;} if(t.startsWith("#"))continue; const bits=t.split(/\s*->\s*/); if(bits.length!==3)continue; let [a,rr,b]=bits; rr=rr.trim().replace(/\*/g,""); let confidence:null|1|2|3|4|5=null; const cm=b.match(/\s+@([1-5])\b/);if(cm){confidence=Number(cm[1]) as any;b=b.replace(cm[0],"");} const anchors:{source_id:string;locator?:string}[]=[]; b=b.replace(/\s+\[([^\]]+)\]/g,(_,v)=>{const z=v.trim().split(/\s+/);anchors.push({source_id:z[0],...(z.slice(1).length?{locator:z.slice(1).join(" ")}:{})});return "";}); let justification:null|string=null; b=b.replace(/\s+\/\/\s*(.*)$/,( _,v)=>{justification=v.trim();return "";}); a=a.trim();b=b.trim(); const sid=getConcept(a),oid=getConcept(b); let rel:string|{free:string}=ix.r.get(norm(rr))||{free:rr}; let subject=sid,object=oid; if(typeof rel==="string"&&rel.startsWith("!")){rel=rel.slice(1);[subject,object]=[object,subject];} const key=`${subject}|${JSON.stringify(rel)}|${object}`; const prior=byKey.get(key); out.propositions.push({id:prior?.id||nextId(),subject,relation:rel,object,confidence,justification,anchors,learned_at:prior?.learned_at||now,holds_from:null,holds_to:null,status:prior?.status||"asserted",derived_from:prior?.derived_from||null});}
 out.concepts=[...concepts.values()]; return out;
}
export function printSentences(map:MapDoc,pack:Pack):string{const q=map.focus_question?`? ${map.focus_question}\n`:""; return q+map.propositions.map(p=>{let s=`${conceptLabel(p.subject,pack,map)} -> ${relLabel(p.relation,pack)} -> ${conceptLabel(p.object,pack,map)}`;if(p.confidence)s+=`  @${p.confidence}`;for(const a of p.anchors)s+=`  [${a.source_id}${a.locator?` ${a.locator}`:""}]`;if(p.justification)s+=`  // ${p.justification}`;return s;}).join("\n");}
export type Structure={concepts:number;propositions:number;components:number;cycles:number;diameter:number;hub:string;hub_degree:number;spoke:number;chain:number;degree2:number;roots:string[];free:number;weak:number;orphans:string[];density:number;degrees:Record<string,number>;label:"network"|"spoke"|"chain"|"tree";cross_link:boolean;derivation:string[]};
export function diagnoseStructure(map:MapDoc,pack:Pack):Structure{
 const ns=map.concepts.map(c=>c.id);
 const deg=new Map(ns.map(n=>[n,0]));
 const adj=new Map(ns.map(n=>[n,new Set<string>()]));
 for(const p of map.propositions){deg.set(p.subject,(deg.get(p.subject)||0)+1);deg.set(p.object,(deg.get(p.object)||0)+1);adj.get(p.subject)?.add(p.object);adj.get(p.object)?.add(p.subject);}
 let comps=0;const seen=new Set<string>();
 for(const n of ns)if(!seen.has(n)){comps++;const q=[n];seen.add(n);while(q.length){for(const x of adj.get(q.shift()!)||[])if(!seen.has(x)){seen.add(x);q.push(x)}}}
 let diameter=0;
 for(const s of ns){const d=new Map([[s,0]]),q=[s];while(q.length){const x=q.shift()!;for(const y of adj.get(x)||[])if(!d.has(y)){d.set(y,d.get(x)!+1);q.push(y)}}diameter=Math.max(diameter,...d.values());}
 const hub=ns.slice().sort((a,b)=>(deg.get(b)||0)-(deg.get(a)||0))[0]||"";
 const cycles=map.propositions.length-ns.length+comps;
 const spoke=map.propositions.length?(deg.get(hub)||0)/map.propositions.length:0;
 const chain=ns.length?ns.filter(n=>deg.get(n)===2).length/ns.length:0;
 const hierarchical=map.propositions.flatMap(p=>{const r=typeof p.relation==="string"?pack.relations.find(x=>x.id===p.relation):undefined;if(!r?.hierarchy_weight)return[];return[{edge:p,parent:r.hierarchy_weight===1?p.subject:p.object,child:r.hierarchy_weight===1?p.object:p.subject}]});
 const childIds=new Set(hierarchical.map(x=>x.child));
 const roots=ns.filter(n=>!childIds.has(n));
 const branch=new Map<string,string>();
 const down=new Map<string,string[]>();
 for(const h of hierarchical){const children=down.get(h.parent)||[];children.push(h.child);down.set(h.parent,children);}
 for(const root of roots){for(const first of down.get(root)||[]){const q=[first];while(q.length){const n=q.shift()!;if(branch.has(n))continue;branch.set(n,first);q.push(...(down.get(n)||[]));}}}
 const hierarchicalIds=new Set(hierarchical.map(x=>x.edge.id));
 const cross=map.propositions.some(p=>!hierarchicalIds.has(p.id)&&branch.has(p.subject)&&branch.has(p.object)&&branch.get(p.subject)!==branch.get(p.object));
 const free=map.propositions.filter(p=>typeof p.relation!=="string").length;
 const weak=map.propositions.filter(p=>p.relation==="is-related-to").length;
 const degrees=Object.fromEntries(ns.slice().sort((a,b)=>(deg.get(b)||0)-(deg.get(a)||0)).map(n=>[conceptLabel(n,pack),deg.get(n)||0]));
 const label=cycles>=1||cross?"network":spoke>=.5?"spoke":chain>=.5?"chain":"tree";
 return {concepts:ns.length,propositions:map.propositions.length,components:comps,cycles,diameter,hub:conceptLabel(hub,pack),hub_degree:deg.get(hub)||0,spoke:+spoke.toFixed(2),chain:+chain.toFixed(2),degree2:ns.filter(n=>deg.get(n)===2).length,roots:roots.map(n=>conceptLabel(n,pack)),free,weak,orphans:ns.filter(n=>!deg.get(n)).map(n=>conceptLabel(n,pack)),density:+(ns.length?map.propositions.length/ns.length:0).toFixed(2),degrees,label,cross_link:cross,derivation:[`Counted ${ns.length} concepts, ${map.propositions.length} propositions, and ${comps} connected components.`,`Independent cycles = propositions - concepts + components = ${map.propositions.length} - ${ns.length} + ${comps} = ${cycles}.`,`Shape is ${label}${cross?" because a non-hierarchy edge crosses root branches":""}.`]};
}
export type Finding={message:string;derivation:string[];related_ids:string[]};
export type Inference={implied:{subject:string;relation:string;object:string;derivation:string;derived_from:string[]}[];conflicts:Finding[];taxonomic_cycles:Finding[];ill_typed:Finding[];derivation:string[]};
export function infer(map:MapDoc,pack:Pack):Inference{
 const rels=new Map(pack.relations.map(r=>[r.id,r]));
 const facts=new Set<string>();
 const provenance=new Map<string,string[]>();
 for(const p of map.propositions)if(typeof p.relation==="string"){const key=`${p.subject}|${p.relation}|${p.object}`;facts.add(key);provenance.set(key,[p.id]);}
 const why=new Map<string,string>();
 let changed=true;
 while(changed){changed=false;for(const x of [...facts])for(const y of [...facts]){
  const [a,r,b]=x.split("|"),[c,s,d]=y.split("|"),rr=rels.get(r);if(!rr||b!==c)continue;
  let t="",reason="";
  if(r===s&&rr.transitive){t=`${a}|${r}|${d}`;reason=`${conceptLabel(a,pack)} ${relLabel(r,pack)} ${conceptLabel(b,pack)}; ${conceptLabel(b,pack)} ${relLabel(r,pack)} ${conceptLabel(d,pack)} (${relLabel(r,pack)} is transitive)`;}
  else if(pack.inference?.inheritable_relations.includes(r)&&s===pack.inference.inherit_along){t=`${a}|${r}|${d}`;reason=`${conceptLabel(a,pack)} ${relLabel(r,pack)} ${conceptLabel(b,pack)}; ${conceptLabel(b,pack)} ${relLabel(s,pack)} ${conceptLabel(d,pack)} (${relLabel(r,pack)} inherits along ${relLabel(s,pack)})`;}
  if(t&&!facts.has(t)){facts.add(t);why.set(t,reason);provenance.set(t,[...new Set([...(provenance.get(x)||[]),...(provenance.get(y)||[])])]);changed=true;}
 }}
 const implied=[...why.entries()].map(([key,derivation])=>{const [subject,relation,object]=key.split("|");return {subject,relation,object,derivation,derived_from:provenance.get(key)||[]}});
 const conflicts:Finding[]=[];
 for(const x of facts){const [a,r,b]=x.split("|"),rr=rels.get(r);for(const s of rr?.incompatible_with||[]){const other=`${a}|${s}|${b}`;if(r<s&&facts.has(other)){const message=`${conceptLabel(a,pack)} ${relLabel(r,pack)} ${conceptLabel(b,pack)}  vs  ${conceptLabel(a,pack)} ${relLabel(s,pack)} ${conceptLabel(b,pack)}`;conflicts.push({message,related_ids:[...new Set([...(provenance.get(x)||[]),...(provenance.get(other)||[])])],derivation:[`The loaded pack marks “${relLabel(r,pack)}” and “${relLabel(s,pack)}” as incompatible for the same subject and object.`,message]});}}}
 const taxonomic_cycles:Finding[]=[...facts].filter(x=>{const [a,r,b]=x.split("|");return a===b&&rels.get(r)?.transitive}).map(x=>{const [a,r]=x.split("|");const message=`${conceptLabel(a,pack)} ${relLabel(r,pack)} ${conceptLabel(a,pack)}`;return{message,related_ids:provenance.get(x)||[],derivation:[`Following the transitive relation “${relLabel(r,pack)}” returns to ${conceptLabel(a,pack)}.`,why.get(x)||message]}});
 const ill_typed:Finding[]=[];
 for(const p of map.propositions){if(typeof p.relation!=="string")continue;const r=rels.get(p.relation);if(!r)continue;const st=map.concepts.find(c=>c.id===p.subject)?.type,ot=map.concepts.find(c=>c.id===p.object)?.type;if((r.subject_types.length&&!r.subject_types.includes(st||""))||(r.object_types.length&&!r.object_types.includes(ot||""))){const message=`${conceptLabel(p.subject,pack)} (${st}) ${relLabel(p.relation,pack)} ${conceptLabel(p.object,pack)} (${ot}); relation requires ${r.subject_types.length?r.subject_types.join(", "):"any"} -> ${r.object_types.length?r.object_types.join(", "):"any"}`;ill_typed.push({message,related_ids:[p.id],derivation:[`Checked proposition ${p.id} against the loaded type constraints for “${r.label}”.`,message]});}}
 return {implied,conflicts,taxonomic_cycles,ill_typed,derivation:["Applied transitivity, inheritance, incompatibility, type, and taxonomic-cycle rules from the loaded pack."]};
}
export type Comparison={shared:string[];only_student:string[];only_expert:string[];disputes:string[];recall:number;precision:number;f1:number;goldsmith:number;concepts_shared:number;concepts_student:number;concepts_expert:number;derivation:string[]};
export function compare(student:MapDoc,reference:MapDoc,pack:Pack):Comparison{const key=(p:Proposition)=>`${p.subject}|${typeof p.relation==="string"?p.relation:"free:"+p.relation.free}|${p.object}`, fmt=(k:string)=>{const [a,r,b]=k.split("|");return `${conceptLabel(a,pack)} -> ${r.startsWith("free:")?r:relLabel(r,pack)} -> ${conceptLabel(b,pack)}`};const A=new Set(student.propositions.map(key)),B=new Set(reference.propositions.map(key)),shared=[...A].filter(x=>B.has(x)),oa=[...A].filter(x=>!B.has(x)),ob=[...B].filter(x=>!A.has(x));const pair=(x:string)=>{const z=x.split("|");return [z[0],z[2]].sort().join("|")};const disputes:string[]=[];for(const x of oa)for(const y of ob)if(pair(x)===pair(y))disputes.push(`${fmt(x)}   vs   ${fmt(y)}`);const recall=B.size?shared.length/B.size:0,precision=A.size?shared.length/A.size:0;const nbr=(m:MapDoc)=>{const n=new Map<string,Set<string>>();for(const p of m.propositions){if(!n.has(p.subject))n.set(p.subject,new Set);if(!n.has(p.object))n.set(p.object,new Set);n.get(p.subject)!.add(p.object);n.get(p.object)!.add(p.subject);}return n};const na=nbr(student),nb=nbr(reference),all=new Set([...na.keys(),...nb.keys()]);let gold=0;for(const c of all){const u=new Set([...(na.get(c)||[]),...(nb.get(c)||[])]),i=[...(na.get(c)||[])].filter(x=>nb.get(c)?.has(x)).length;gold+=u.size?i/u.size:1;}return {shared:shared.map(fmt),only_student:oa.map(fmt),only_expert:ob.map(fmt),disputes,recall:+recall.toFixed(2),precision:+precision.toFixed(2),f1:+((recall+precision)?2*recall*precision/(recall+precision):0).toFixed(2),goldsmith:+(all.size?gold/all.size:0).toFixed(2),concepts_shared:new Set([...na.keys()].filter(x=>nb.has(x))).size,concepts_student:na.size,concepts_expert:nb.size,derivation:["Compared canonical subject-relation-object triples and neighbour sets."]};}